<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_614505812295f',
	'title' => 'Background Image',
	'fields' => array(
		array(
			'key' => 'field_614505a61e15d',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'url',
			'preview_size' => 'large',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'library' => 'all',
		),
		array(
			'key' => 'field_614505f91e15f',
			'label' => '',
			'name' => 'image_settings',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_614506081e160',
					'label' => 'Size',
					'name' => 'background_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'bg-auto' => 'Auto',
						'bg-contain' => 'Contain',
						'bg-cover' => 'Cover',
					),
					'default_value' => 'bg-cover',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_614506471e161',
					'label' => 'Position',
					'name' => 'background_position',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'bg-left-top' => 'Left Top',
						'bg-center-top' => 'Center Top',
						'bg-right-top' => 'Right Top',
						'bg-left-center' => 'Left Center',
						'bg-center' => 'Center',
						'bg-right-center' => 'Right Center',
						'bg-left-bottom' => 'Left Bottom',
						'bg-center-bottom' => 'Center Bottom',
						'bg-right-bottom' => 'Right Bottom',
					),
					'default_value' => 'bg-center',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_614506891e162',
					'label' => 'Repeat',
					'name' => 'background_repeat',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'bg-no-repeat' => 'No Repeat',
						'bg-repeat' => 'Repeat',
						'bg-repeat-x' => 'Repeat X',
						'bg-repeat-y' => 'Repeat Y',
					),
					'default_value' => 'bg-no-repeat',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 1,
					'return_format' => 'value',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'settings' => 'Settings',
	),
	'modified' => 1632112124,
));

endif;