<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_609af2236c640',
	'title' => 'Flexible Content',
	'fields' => array(
		array(
			'key' => 'field_609af2c7cde69',
			'label' => 'Layout Items',
			'name' => 'layout_items',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => 'field_609af33bcde6a',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Item',
			'sub_fields' => array(
				array(
					'key' => 'field_609af33bcde6a',
					'label' => 'Content Type',
					'name' => 'content_type',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_flexible_advanced' => 1,
					'acfe_flexible_stylised_button' => 1,
					'acfe_flexible_layouts_templates' => 0,
					'acfe_flexible_layouts_placeholder' => 0,
					'acfe_flexible_layouts_thumbnails' => 0,
					'acfe_flexible_layouts_settings' => 1,
					'acfe_flexible_async' => array(
						0 => 'title',
						1 => 'layout',
					),
					'acfe_flexible_add_actions' => array(
						0 => 'title',
						1 => 'toggle',
						2 => 'copy',
					),
					'acfe_flexible_remove_button' => array(
					),
					'acfe_flexible_layouts_state' => 'user',
					'acfe_flexible_modal_edit' => array(
						'acfe_flexible_modal_edit_enabled' => '0',
						'acfe_flexible_modal_edit_size' => 'large',
					),
					'acfe_flexible_modal' => array(
						'acfe_flexible_modal_enabled' => '1',
						'acfe_flexible_modal_title' => 'Add Content Type',
						'acfe_flexible_modal_size' => 'xlarge',
						'acfe_flexible_modal_col' => '6',
						'acfe_flexible_modal_categories' => '1',
					),
					'layouts' => array(
						'layout_60a41ae81f7ed' => array(
							'key' => 'layout_60a41ae81f7ed',
							'name' => 'text',
							'label' => 'Text',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_60a41af11f7ee',
									'label' => '',
									'name' => 'text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '80',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => 'Text',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_6147ff4cae6bb',
									'label' => '',
									'name' => 'type',
									'type' => 'button_group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '20',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'h1' => 'H1',
										'h2' => 'H2',
										'h3' => 'H3',
										'h4' => 'H4',
										'h5' => 'H5',
										'h6' => 'H6',
										'p' => 'P',
									),
									'allow_null' => 0,
									'default_value' => '',
									'layout' => '',
									'return_format' => '',
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fcf2ca952e',
								1 => 'group_613fc3855ad6c',
								2 => 'group_613efa13331d6',
								3 => 'group_613fce1fc2c57',
								4 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_616528305e78b' => array(
							'key' => 'layout_616528305e78b',
							'name' => 'text-area',
							'label' => 'Text Area',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_616528305e78c',
									'label' => '',
									'name' => 'text',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => 'br',
									'acfe_textarea_code' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fcf2ca952e',
								1 => 'group_613fc3855ad6c',
								2 => 'group_613efa13331d6',
								3 => 'group_613fce1fc2c57',
								4 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_6148facf16347' => array(
							'key' => 'layout_6148facf16347',
							'name' => 'list',
							'label' => 'List',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6148fae116348',
									'label' => 'List Items',
									'name' => 'list_items',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_repeater_stylised_button' => 0,
									'collapsed' => 'field_6148faef16349',
									'min' => 1,
									'max' => 0,
									'layout' => 'block',
									'button_label' => 'Add List Item',
									'sub_fields' => array(
										array(
											'key' => 'field_6148faef16349',
											'label' => 'Item',
											'name' => 'item',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_6148f7cd423b2',
								1 => 'group_613fcf2ca952e',
								2 => 'group_613fc3855ad6c',
								3 => 'group_613efa13331d6',
								4 => 'group_613fce1fc2c57',
								5 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_6147ff7cae6bc' => array(
							'key' => 'layout_6147ff7cae6bc',
							'name' => 'wysiwyg',
							'label' => 'WYSIWYG',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6147ff7cae6bd',
									'label' => '',
									'name' => 'wysiwyg',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '80',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fcf2ca952e',
								1 => 'group_613fc3855ad6c',
								2 => 'group_613efa13331d6',
								3 => 'group_613fce1fc2c57',
								4 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_6147fef9ae6b9' => array(
							'key' => 'layout_6147fef9ae6b9',
							'name' => 'link',
							'label' => 'Link',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6147fef9ae6ba',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '80',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
								array(
									'key' => 'field_614800f3ab3ba',
									'label' => 'Style',
									'name' => 'style',
									'type' => 'button_group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '20',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'link' => 'Link',
										'button' => 'Button',
									),
									'allow_null' => 0,
									'default_value' => 'link',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fcf2ca952e',
								1 => 'group_613fc3855ad6c',
								2 => 'group_613efa13331d6',
								3 => 'group_613fce1fc2c57',
								4 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_613928a9e7103' => array(
							'key' => 'layout_613928a9e7103',
							'name' => 'image',
							'label' => 'Image',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_613928c8e7104',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'uploader' => '',
									'acfe_thumbnail' => 0,
									'return_format' => 'array',
									'preview_size' => 'medium',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'library' => 'all',
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fc3855ad6c',
								1 => 'group_6147b3165ae3c',
								2 => 'group_613efa13331d6',
								3 => 'group_613fce1fc2c57',
								4 => 'group_6147fc6e7869a',
								5 => 'group_614803645f0e7',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_6139154588b37' => array(
							'key' => 'layout_6139154588b37',
							'name' => 'line-separator',
							'label' => 'Line Separator',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6139155f88b38',
									'label' => 'Line Separator',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Click on the settings cog to start applying styles to this component.',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Basic',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fce1fc2c57',
								1 => 'group_6147fc6e7869a',
								2 => 'group_614500f9c8e0e',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_61044a1d6c611' => array(
							'key' => 'layout_61044a1d6c611',
							'name' => 'shortcode',
							'label' => 'Shortcode',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_61044a436c612',
									'label' => 'Shortcode',
									'name' => 'shortcode',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Third-Party',
								1 => 'Basic',
							),
							'acfe_flexible_settings' => '',
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_613a6deeba94e' => array(
							'key' => 'layout_613a6deeba94e',
							'name' => 'wrapper',
							'label' => 'Wrapper (Start)',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6147adb763122',
									'label' => '',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Click the settings cog in the top right of this component to customize the wrapper options.',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Specialty',
								1 => 'Wrapper',
							),
							'acfe_flexible_settings' => array(
								0 => 'group_613fc3855ad6c',
								1 => 'group_613efa13331d6',
								2 => 'group_613fce1fc2c57',
								3 => 'group_6147fc6e7869a',
							),
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
						'layout_613a6e1bba950' => array(
							'key' => 'layout_613a6e1bba950',
							'name' => 'wrapper_end',
							'label' => 'Wrapper (End)',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_613a6e1bba951',
									'label' => '',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Closes the wrapper component. All options are configurable inside the starting component.',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_category' => array(
								0 => 'Specialty',
								1 => 'Wrapper',
							),
							'acfe_flexible_settings' => '',
							'acfe_flexible_settings_size' => 'large',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_modal_edit_size' => false,
						),
					),
					'button_label' => 'Add Content',
					'min' => '',
					'max' => '',
					'acfe_flexible_hide_empty_message' => false,
					'acfe_flexible_empty_message' => '',
					'acfe_flexible_layouts_previews' => false,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'category:uncategorized',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'layout' => 'Layout',
	),
	'modified' => 1634277437,
));

endif;