<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_604920e3356bb',
	'title' => 'Page Banner',
	'fields' => array(
		array(
			'key' => 'field_60524604d5e8a',
			'label' => '',
			'name' => 'page-banner_group',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_60492117c3928',
					'label' => 'Banner Type',
					'name' => 'page-banner_banner-type',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'None/Disabled',
						'text' => 'Text Only',
						'image' => 'Image Only',
						'image-text' => 'Image w/ Text',
						'video' => 'Video',
						'shortcode' => 'Shortcode',
						'content-block' => 'Content Block',
					),
					'allow_null' => 0,
					'default_value' => 'none',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_604924c76873a',
					'label' => 'Style',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'none',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'content-block',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'shortcode',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_605e27a68e9f2',
					'label' => 'Text Color',
					'name' => 'page-banner_text-color',
					'type' => 'extended-color-picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'color_palette' => '',
					'hide_palette' => 0,
				),
				array(
					'key' => 'field_605e27b68e9f3',
					'label' => 'Background Color',
					'name' => 'page-banner_background-color',
					'type' => 'extended-color-picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'color_palette' => '',
					'hide_palette' => 0,
				),
				array(
					'key' => 'field_604949f373da9',
					'label' => 'Poster',
					'name' => 'page-banner_poster',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60494a0e73daa',
					'label' => 'Video',
					'name' => 'page-banner_video',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'wp',
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_604925bd6873c',
					'label' => 'Image',
					'name' => 'page-banner_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'none',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'video',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6049262f6873e',
					'label' => 'Image (Mobile)',
					'name' => 'page-banner_image-mobile',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'none',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'video',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_60493dda817ae',
					'label' => 'Image Position',
					'name' => 'page-banner_image-position',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'image-text',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left top' => 'Left Top',
						'center top' => 'Center Top',
						'right top' => 'Right Top',
						'left center' => 'Left Center',
						'center' => 'Center',
						'right center' => 'Right Center',
						'left bottom' => 'Left Bottom',
						'center bottom' => 'Center Bottom',
						'right bottom' => 'Right Bottom',
					),
					'default_value' => 'center',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60493e2e817af',
					'label' => 'Top/Bottom Padding (px)',
					'name' => 'page-banner_top-bottom-padding',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'image-text',
							),
						),
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => 140,
					'min' => 0,
					'max' => 200,
					'step' => 1,
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_604922cfa2b15',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'none',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_60524539b60d9',
					'label' => 'Content Block',
					'name' => 'content_block',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'content-block',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'content-block',
					),
					'taxonomy' => array(
						0 => 'block-type:page-banner',
					),
					'allow_null' => 1,
					'multiple' => 0,
					'return_format' => 'object',
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'ui' => 1,
				),
				array(
					'key' => 'field_60527b3f7a8fb',
					'label' => 'Shortcode',
					'name' => 'page-banner_shortcode',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'shortcode',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_60492351a2b17',
					'label' => 'Banner Text',
					'name' => 'page-banner_banner-text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'none',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'image',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'content-block',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '!=',
								'value' => 'shortcode',
							),
						),
					),
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_604923aba2b18',
					'label' => 'Banner Link',
					'name' => 'page-banner_banner-link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Enabled',
					'ui_off_text' => 'Disabled',
				),
				array(
					'key' => 'field_604923d6a2b19',
					'label' => 'Link',
					'name' => 'page-banner_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_604923aba2b18',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_60492117c3928',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'block-type:page-header',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'advanced-builder.php',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'layout' => 'Layout',
	),
	'modified' => 1632112333,
));

endif;