<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_612ff8ca6d684',
	'title' => 'Layout Settings',
	'fields' => array(
		array(
			'key' => 'field_613129daf8c79',
			'label' => 'Layout Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_613a8cde9bc94',
			'label' => 'Layout Type',
			'name' => 'layout_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'standard' => 'Standard',
				'masonry' => 'Masonry',
				'custom' => 'Custom',
			),
			'allow_null' => 0,
			'default_value' => 'standard',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_614f93780a761',
			'label' => 'Standard Columns',
			'name' => 'standard_columns',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_613a8cde9bc94',
						'operator' => '==',
						'value' => 'standard',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_614f93920a762',
					'label' => 'Desktop',
					'name' => 'desktop',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'columns-1' => '1',
						'columns-2' => '2',
						'columns-3' => '3',
						'columns-4' => '4',
						'columns-5' => '5',
						'columns-6' => '6',
						'columns-1-2' => '1:2',
						'columns-1-3' => '1:3',
						'columns-1-4' => '1:4',
						'columns-2-1' => '2:1',
						'columns-2-3' => '2:3',
						'columns-3-1' => '3:1',
						'columns-3-2' => '3:2',
						'columns-4-1' => '4:1',
					),
					'allow_null' => 0,
					'default_value' => 'columns-1',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_614f9df50a766',
					'label' => 'Tablet',
					'name' => 'tablet',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'tablet-columns-1' => '1',
						'tablet-columns-2' => '2',
						'tablet-columns-3' => '3',
						'tablet-columns-4' => '4',
						'tablet-columns-5' => '5',
						'tablet-columns-6' => '6',
						'tablet-columns-1-2' => '1:2',
						'tablet-columns-1-3' => '1:3',
						'tablet-columns-1-4' => '1:4',
						'tablet-columns-2-1' => '2:1',
						'tablet-columns-2-3' => '2:3',
						'tablet-columns-3-1' => '3:1',
						'tablet-columns-3-2' => '3:2',
						'tablet-columns-4-1' => '4:1',
					),
					'allow_null' => 0,
					'default_value' => 'tablet-columns-1',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_614f9e250a767',
					'label' => 'Mobile',
					'name' => 'mobile',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'mobile-columns-1' => '1',
						'mobile-columns-2' => '2',
						'mobile-columns-3' => '3',
						'mobile-columns-4' => '4',
						'mobile-columns-5' => '5',
						'mobile-columns-6' => '6',
						'mobile-columns-1-2' => '1:2',
						'mobile-columns-1-3' => '1:3',
						'mobile-columns-1-4' => '1:4',
						'mobile-columns-2-1' => '2:1',
						'mobile-columns-2-3' => '2:3',
						'mobile-columns-3-1' => '3:1',
						'mobile-columns-3-2' => '3:2',
						'mobile-columns-4-1' => '4:1',
					),
					'allow_null' => 0,
					'default_value' => 'mobile-columns-1',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_616923223394a',
			'label' => 'Masonry Columns',
			'name' => 'masonry_columns',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_613a8cde9bc94',
						'operator' => '==',
						'value' => 'masonry',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_616923223394b',
					'label' => 'Desktop',
					'name' => 'desktop',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'columns-2' => '2',
						'columns-3' => '3',
						'columns-4' => '4',
						'columns-5' => '5',
						'columns-6' => '6',
					),
					'allow_null' => 0,
					'default_value' => 'columns-3',
					'layout' => 'horizontal',
					'return_format' => 'array',
				),
				array(
					'key' => 'field_616923223394c',
					'label' => 'Tablet',
					'name' => 'tablet',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'tablet-columns-1' => '1',
						'tablet-columns-2' => '2',
						'tablet-columns-3' => '3',
						'tablet-columns-4' => '4',
						'tablet-columns-5' => '5',
						'tablet-columns-6' => '6',
					),
					'allow_null' => 0,
					'default_value' => 'tablet-columns-2',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_616923223394d',
					'label' => 'Mobile',
					'name' => 'mobile',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'mobile-columns-1' => '1',
						'mobile-columns-2' => '2',
						'mobile-columns-3' => '3',
						'mobile-columns-4' => '4',
						'mobile-columns-5' => '5',
						'mobile-columns-6' => '6',
					),
					'allow_null' => 0,
					'default_value' => 'mobile-columns-1',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_61453b9d4d12d',
			'label' => 'Vertical Alignment',
			'name' => 'vertical-alignment',
			'type' => 'button_group',
			'instructions' => 'Vertically align elements in the same row in regards to the tallest row.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_613a8cde9bc94',
						'operator' => '==',
						'value' => 'standard',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'unset' => 'Top',
				'valign-center' => 'Center',
				'valign-bottom' => 'Bottom',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_6148eb66768bc',
			'label' => 'Layout ID',
			'name' => 'layout_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_616915a4c7d97',
			'label' => 'Layout Class(es)',
			'name' => 'layout_classes',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_616915fac7d98',
			'label' => 'Layout Item Class(es)',
			'name' => 'layout_item_classes',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'category:uncategorized',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => 'Settings and styles for the grid layout used in [Layout] Flexible Grid. Adds the ability to manage design aspects for the Flexible Grid layout directly inside the WordPress backend.',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'settings' => 'Settings',
	),
	'modified' => 1635201236,
));

endif;