<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5faed9d9c2044',
	'title' => 'Slider',
	'fields' => array(
		array(
			'key' => 'field_5faedb02ae397',
			'label' => 'Adaptive Height',
			'name' => 'adaptive_height',
			'type' => 'true_false',
			'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faeda19ae393',
			'label' => 'Autoplay',
			'name' => 'autoplay',
			'type' => 'true_false',
			'instructions' => 'Enables Autoplay',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faeda6cae394',
			'label' => 'Autoplay Speed',
			'name' => 'autoplay_speed',
			'type' => 'number',
			'instructions' => 'Autoplay Speed in milliseconds',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 3000,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_5faeda89ae395',
			'label' => 'Arrows',
			'name' => 'arrows',
			'type' => 'true_false',
			'instructions' => 'Prev/Next Arrows',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedf615459d',
			'label' => 'As Nav For',
			'name' => 'as_nav_for',
			'type' => 'text',
			'instructions' => 'Set the slider to be the navigation of other slider (Class or ID Name)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5faedab0ae396',
			'label' => 'Center Mode',
			'name' => 'center_mode',
			'type' => 'true_false',
			'instructions' => 'Enables centered view with partial prev/next slides. Use with odd numbered slidesToShow counts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedb24ae398',
			'label' => 'Center Padding (px)',
			'name' => 'center_padding',
			'type' => 'number',
			'instructions' => 'Side padding when in center mode (px or %)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 50,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5faedb89ae399',
			'label' => 'Dots',
			'name' => 'dots',
			'type' => 'true_false',
			'instructions' => 'Show dot indicators',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedb9cae39a',
			'label' => 'Draggable',
			'name' => 'draggable',
			'type' => 'true_false',
			'instructions' => 'Enable mouse dragging',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedbafae39b',
			'label' => 'Fade',
			'name' => 'fade',
			'type' => 'true_false',
			'instructions' => 'Enable fade',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedbceae39c',
			'label' => 'Infinite',
			'name' => 'infinite',
			'type' => 'true_false',
			'instructions' => 'Infinite loop sliding',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedbe9ae39d',
			'label' => 'Pause on Focus',
			'name' => 'pause_on_focus',
			'type' => 'true_false',
			'instructions' => 'Pause Autoplay On Focus',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedbfaae39e',
			'label' => 'Pause on Hover',
			'name' => 'pause_on_hover',
			'type' => 'true_false',
			'instructions' => 'Pause Autoplay On Hover',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedc1fae39f',
			'label' => 'Slides to Show',
			'name' => 'slides_to_show',
			'type' => 'number',
			'instructions' => '# of slides to show',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5faedc33ae3a0',
			'label' => 'Slides to Scroll',
			'name' => 'slides_to_scroll',
			'type' => 'number',
			'instructions' => '# of slides to scroll',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5faedc49ae3a1',
			'label' => 'Speed',
			'name' => 'speed',
			'type' => 'number',
			'instructions' => 'Slide/Fade animation speed',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => 300,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 250,
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_5faedcfcae3a2',
			'label' => 'Swipe',
			'name' => 'swipe',
			'type' => 'true_false',
			'instructions' => 'Enable swiping',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedd18ae3a3',
			'label' => 'Variable Width',
			'name' => 'variable_width',
			'type' => 'true_false',
			'instructions' => 'Variable width slides',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedd2eae3a4',
			'label' => 'Vertical',
			'name' => 'vertical',
			'type' => 'true_false',
			'instructions' => 'Vertical slide mode',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedd5bae3a5',
			'label' => 'Vertical Swiping',
			'name' => 'vertical_swiping',
			'type' => 'true_false',
			'instructions' => 'Vertical swipe mode',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5faedfe869c6e',
			'label' => 'Responsiveness (Tablet)',
			'name' => 'responsiveness_tablet',
			'type' => 'true_false',
			'instructions' => 'Enables responsiveness at the tablet breakpoint (1024 pixels)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5fb4141a32481',
			'label' => 'Responsiveness (Mobile)',
			'name' => 'responsiveness_mobile',
			'type' => 'true_false',
			'instructions' => 'Enables responsiveness at the mobile breakpoint (768 pixels)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'True',
			'ui_off_text' => 'False',
		),
		array(
			'key' => 'field_5fb4147e5c5b0',
			'label' => 'Tablet',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5faedfe869c6e',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fb4133c187cb',
			'label' => 'Responsiveness (Tablet)',
			'name' => 'group-responsiveness_tablet',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5faedfe869c6e',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5faee17f04b09',
					'label' => 'Adaptive Height',
					'name' => 'tablet-adaptive_height',
					'type' => 'true_false',
					'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5faee02f69c70',
					'label' => 'Autoplay',
					'name' => 'tablet-autoplay',
					'type' => 'true_false',
					'instructions' => 'Enables Autoplay',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5faee04969c71',
					'label' => 'Autoplay Speed',
					'name' => 'tablet-autoplay_speed',
					'type' => 'number',
					'instructions' => 'Autoplay Speed in milliseconds',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 3000,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 50,
				),
				array(
					'key' => 'field_5faee08b69c72',
					'label' => 'Arrows',
					'name' => 'tablet-arrows',
					'type' => 'true_false',
					'instructions' => 'Prev/Next Arrows',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5faee0a069c73',
					'label' => 'Center Mode',
					'name' => 'tablet-center_mode',
					'type' => 'true_false',
					'instructions' => 'Enables centered view with partial prev/next slides. Use with odd numbered slidesToShow counts.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5faee0b469c74',
					'label' => 'Center Padding (px)',
					'name' => 'tablet-center_padding',
					'type' => 'number',
					'instructions' => 'Side padding when in center mode (px or %)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 50,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5faee0d369c75',
					'label' => 'Dots',
					'name' => 'tablet-dots',
					'type' => 'true_false',
					'instructions' => 'Show dot indicators',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb56e11fd435',
					'label' => 'Draggable',
					'name' => 'tablet-draggable',
					'type' => 'true_false',
					'instructions' => 'Enable mouse dragging',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb56e28fd436',
					'label' => 'Fade',
					'name' => 'tablet-fade',
					'type' => 'true_false',
					'instructions' => 'Enable fade',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5faee0e969c76',
					'label' => 'Slides to Show',
					'name' => 'tablet-slides_to_show',
					'type' => 'number',
					'instructions' => '# of slides to show',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5faee0fc69c77',
					'label' => 'Slides to Scroll',
					'name' => 'tablet-slides_to_scroll',
					'type' => 'number',
					'instructions' => '# of slides to scroll',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5faee10e69c78',
					'label' => 'Speed',
					'name' => 'tablet-speed',
					'type' => 'number',
					'instructions' => 'Slide/Fade animation speed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 300,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 250,
					'max' => '',
					'step' => 50,
				),
			),
		),
		array(
			'key' => 'field_5fb414875c5b1',
			'label' => 'Mobile',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fb4141a32481',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fb4142d32482',
			'label' => 'Responsiveness (Mobile)',
			'name' => 'group-responsiveness_mobile',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fb4141a32481',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5fb4142d32483',
					'label' => 'Adaptive Height',
					'name' => 'mobile-adaptive_height',
					'type' => 'true_false',
					'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb4142d32484',
					'label' => 'Autoplay',
					'name' => 'mobile-autoplay',
					'type' => 'true_false',
					'instructions' => 'Enables Autoplay',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb4142d32485',
					'label' => 'Autoplay Speed',
					'name' => 'mobile-autoplay_speed',
					'type' => 'number',
					'instructions' => 'Autoplay Speed in milliseconds',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 3000,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 50,
				),
				array(
					'key' => 'field_5fb4142d32486',
					'label' => 'Arrows',
					'name' => 'mobile-arrows',
					'type' => 'true_false',
					'instructions' => 'Prev/Next Arrows',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb4142d32487',
					'label' => 'Center Mode',
					'name' => 'mobile-center_mode',
					'type' => 'true_false',
					'instructions' => 'Enables centered view with partial prev/next slides. Use with odd numbered slidesToShow counts.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb4142d32488',
					'label' => 'Center Padding (px)',
					'name' => 'mobile-center_padding',
					'type' => 'number',
					'instructions' => 'Side padding when in center mode (px or %)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 50,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5fb4142e32489',
					'label' => 'Dots',
					'name' => 'mobile-dots',
					'type' => 'true_false',
					'instructions' => 'Show dot indicators',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb56eaf4c46e',
					'label' => 'Draggable',
					'name' => 'mobile-draggable',
					'type' => 'true_false',
					'instructions' => 'Enable mouse dragging',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb56ecb4c46f',
					'label' => 'Fade',
					'name' => 'mobile-fade',
					'type' => 'true_false',
					'instructions' => 'Enable fade',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'True',
					'ui_off_text' => 'False',
				),
				array(
					'key' => 'field_5fb4142e3248a',
					'label' => 'Slides to Show',
					'name' => 'mobile-slides_to_show',
					'type' => 'number',
					'instructions' => '# of slides to show',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5fb4142e3248b',
					'label' => 'Slides to Scroll',
					'name' => 'mobile-slides_to_scroll',
					'type' => 'number',
					'instructions' => '# of slides to scroll',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5fb4142e3248c',
					'label' => 'Speed',
					'name' => 'mobile-speed',
					'type' => 'number',
					'instructions' => 'Slide/Fade animation speed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 300,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 250,
					'max' => '',
					'step' => 50,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => false,
	'description' => 'All (necessary) slider settings provided via the Slick Carousel JavaScript library. Integrates all the options for a slider into custom fields that allow for easy updates as needed.',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'settings' => 'Settings',
	),
	'modified' => 1631912144,
));

endif;